repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # use the latest stable version available
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # use the latest stable version available
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # or the latest compatible release
    hooks:
      - id: flake8
